/etc/cloudflared/config.yml

tunnel: <TUNNEL_UUID>                # insert UUID
credentials-file: /etc/cloudflared/<TUNNEL_UUID>.json

ingress:
  - hostname: smart-monitor.anselemokeke.dpdns.org
    service: http://localhost:80      # Nginx on loopback (recommended)
  - service: http_status:404

