version: "3.8"

services:
    sqliteweb:
        image: ghcr.io/coleifer/sqlite-web:latest
        container_name: sqliteweb
        restart: unless-stopped
        ports:
            - "${HOST_PORT}:8080" #guest vm port:container_port
        environment:
            SQLITE_DATABASE: "${DB_FILE}"
        volumes:
            - ${DB_FOLDER:?DB_FOLDER not set}:/data:Z,ro # mount DB folder as read-only, and any persion issues ad :Z,ro to bind mount
            - ${LOG_FOLDER:?LOG_FOLDER not set}:/var/log/sqliteweb # persist logs here, :?… makes Compose fail fast if typo in var
        command: >
         sh -c "mkdir -p /var/log/sqliteweb &&
         sqlite_web -H 0.0.0.0 -p 8080 --read-only /data/$${SQLITE_DATABASE}
         > /var/log/sqliteweb/access.log 2>&1"

    ngrok:
        image: ngrok/ngrok:latest
        container_name: ngrok-sqliteweb
        restart: unless-stopped
        depends_on:
            - sqliteweb
        environment:
            NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
        ports:
            - "4040:4040"
        command: ["start", "--all", "--config", "/etc/ngrok/ngrok.yml"]
        volumes:
            - ./ngrok/ngrok.yml:/etc/ngrok/ngrok.yml:ro
volumes:
    sqliteweb_logs:  # named volume for sqliteweb logs



