name: Build Linux Orchestrator Image

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'platform_infra/docker/orchestrator.linux.Dockerfile'
      - 'platform_infra/docker/entrypoint.sh'
      - 'platform_infra/docker/healthcheck.py'
      - 'scripts/**'
      - 'config/**'
      - 'db/**'
      - 'utils/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      IMAGE_NAME: smartmon-orchestrator
      VERSION: 1.0.0-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (versioned)
        run: |
          IMAGE_DH=anselemo/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          IMAGE_GH=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

          docker buildx build \
            --platform linux/amd64 \
            --target linux \
            -f platform_infra/docker/orchestrator.linux.Dockerfile \
            -t $IMAGE_DH \
            -t $IMAGE_GH \
            --push .

      # (Optional) Create :latest in GHCR AFTER the GHCR package exists
      - name: Tag GHCR :latest from GHCR version (optional)
        run: |
          IMAGE_GH_VER=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          IMAGE_GH_LATEST=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
          docker buildx imagetools create -t $IMAGE_GH_LATEST $IMAGE_GH_VER


