name: Build Linux Orchestrator Image

permissions:
  contents: read
  packages: write    # needed to push to GHCR

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'platform_infra/docker/orchestrator.Dockerfile'
      - 'platform_infra/docker/entrypoint.sh'
      - 'platform_infra/docker/healthcheck.py'
      - 'scripts/**'
      - 'config/**'
      - 'db/**'
      - 'utils/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      IMAGE_NAME: smartmon-orchestrator
      VERSION: 1.0.0-linux

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Docker Hub login
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # GHCR login (use PAT if provided; else fallback to GITHUB_TOKEN)
      - name: Login to GHCR with PAT (preferred)
        if: secrets.GHCR_PAT != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Login to GHCR with GITHUB_TOKEN (fallback)
        if: secrets.GHCR_PAT == ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (versioned + latest)
        run: |
          IMAGE_DH=anselemo/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          IMAGE_GH=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

          docker buildx build \
            --platform linux/amd64 \
            --target linux \
            -f platform_infra/docker/orchestrator.Dockerfile \
            -t $IMAGE_DH \
            -t $IMAGE_GH \
            --push .

          # Optional "latest" tags — comment out if your org blocks creating new packages/tags
          docker buildx imagetools create \
            -t anselemo/${{ env.IMAGE_NAME }}:latest \
            -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest \
            $IMAGE_DH

